language: node_js
node_js:
- '0.11'
- '0.10'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: knGr9Xq1q1wrtxtqDtONBrQJSyBSFp01CgKOWYozNbQ+8hl8IwMAdcZldvnlO+fNvqeo6du/JVGHDA9uKpnbM2TcVYzf2gXzyUVtXXqbn9d4Ik0DsAOZ8fVK2NCk4EP6Pe8iTsAzbC0vA+ICjpZ9sQaNyv5oTpTUFQeppbz0bmxF74loLV9r4n0ennlHyEzGpeXZDfsQKy8o1QSO4Pw4Qm8vIPat/n96UxtlFjH877EU7sAGE+OYfkJ0jriKE4YTbVY920EA5uta+LFFlXU+j0zd4x/Tu1O9+thuhLpeh2MBfD6uhqYdwrhfoFNuHDnycxylBqHhUE35k6duN2FHS2zhkhFSepRv8LJwPLFldQx90ywo9Q8YxvNdUoKUl5gkJDbWTmvH2Lwt6pIp3Y6iPQ2k9cSRwJS6sYCMFHyT7ZEB1PxsQy/e0gXwX4AJwWi6YrPIC2GNxVS3EuBTKdHkycw3iiXK+tecSoHVqjTr+xWED42OKGs9/Gkdl4hSopTgG3ruspdcoTilemYtbVlUmCDSy+OuhuAWmAl9+F8xaRCK4Z21C0zwmCVn0p8Fu54iBhTIF9gefdhWRD2flFVfw9awlkYP4Qfkp5+5F17TUN14Z5Bsu4PdEzzWD7vqH/zw1Zir2oxI3r0W6BeCL1RJrIIrs1bYMe5dC3zaen4G4lU=
  app: switchbook
  on:
    repo: lfaudreejr/switchbook
env:
  global:
    secure: kC81kA+6pyh8b+rdcZwGAC0S0tH6hX3cH8EQVXlcRGGGALnyQG7WnxQf0GwnizE+JIvXC4fZ4VuM0I/QF23tfKVqb7gikoUq4zxcIwWqLAU5ynaKt1BE5jU/RrY2pyIsrteFT1Ia1ORE+480XYkZxS80baLUMDySA2qJhrzddIxjGeR3a3BxUcJmTl2Vmjk+hT19lbG/cVgrzGfXZ8x6dZAWIn9bf6m8/stAfx1XtPZ07GZ5qdwqS2mGQtKKQFFuxFxvOVSLrCAbsHX4+j2aJrJ17/FEY69wuXMz8AdrQl77TAGQrXHtYX4Q2K+bP+g48M1c1mtRLy6iiQNYET34OVUe++I8UOzW/1VijTIPe2qcQ+jOENIkausVkrl0nc+Sb24AMzQBeZzhLgmj1bMxbe1itfV8u3JgnNORpDOaMwNCs+wOHS5C/2rpF06l5lU9UdFTpKdtDZpUyfA7PC2a4EsutTd/v/RVRAzqKp37/yZDlMWKDS15DInr04vdlKhnji0ZqR4wu5vdR8ZuvaCwFRCJw3DQMAmsZApYQFSs+fSPgsWhFxCKV9B/lTNBiLYrDQ1J8G2YsqTXCUggKM8hMbGA7qArkaA2b+TyVLf1ni1nMGVR51ZyHg7SYcZJv4Bhniyo71XWW6RmfvkQMxz33dDDZAoTOcb/+Q0ZJaEn0OE=
